# Self-Hosted Docker Compose (Production)
# Optimized for Unraid with health checks and proper dependencies
version: "3.8"

services:
  kroki:
    image: yuzutech/kroki
    container_name: notes-kroki
    restart: unless-stopped
    ports:
      - "8001:8000" # Kroki service on port 8001
    environment:
      - KROKI_SAFE_MODE=unsafe
    networks:
      - notes-network
    volumes:
      - kroki_cache:/tmp

  docs:
    image: squidfunk/mkdocs-material
    container_name: notes-docs
    restart: unless-stopped
    ports:
      - "8090:8000" # Documentation on port 8090
    volumes:
      - ./docs:/docs/docs:ro
      - ./mkdocs.yml:/docs/mkdocs.yml:ro
      - ./overrides:/docs/overrides:ro
      - notes_site:/docs/site
    command: serve --dev-addr=0.0.0.0:8000 --livereload
    depends_on:
      - kroki
    networks:
      - notes-network
    environment:
      - LIVE_RELOAD_SUPPORT=true
      - FAST_MODE=true

volumes:
  kroki_cache:
  notes_site:

networks:
  notes-network:
    driver: bridge
