# Self-Hosted Docker Compose (Production)
version: "3.8"

services:
  kroki:
    image: yuzutech/kroki
    container_name: notes-kroki
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - KROKI_SAFE_MODE=unsafe
    networks:
      - notes-network
    volumes:
      - kroki_cache:/tmp

  docs:
    image: squidfunk/mkdocs-material
    container_name: notes-docs
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./docs:/docs/docs:ro
      - ./mkdocs.yml:/docs/mkdocs.yml:ro
      - ./requirements.txt:/docs/requirements.txt:ro
      - notes_site:/docs/site
    command: serve --dev-addr=0.0.0.0:8000 --livereload
    depends_on:
      - kroki
    networks:
      - notes-network
    environment:
      - LIVE_RELOAD_SUPPORT=true
      - FAST_MODE=true

  # Optional: Add nginx reverse proxy for custom domain/SSL
  nginx:
    image: nginx:alpine
    container_name: notes-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - docs
    networks:
      - notes-network

volumes:
  kroki_cache:
  notes_site:

networks:
  notes-network:
    driver: bridge
