site_name: Documentation Site
site_description: Modern documentation with MkDocs Material and Kroki
site_author: Your Team
site_url: https://your-username.github.io/your-repo

# Repository
repo_name: your-username/your-repo
repo_url: https://github.com/your-username/your-repo
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Plugins
plugins:
  - search

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guides:
    - Authoring: guides/authoring.md
  - Diagrams:
    - Mermaid: diagrams/mermaid.md
    - PlantUML: diagrams/plantuml.md
  - My Notes:
    - First Note: my-first-note.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/your-repo
  generator: false

extra_javascript:
  - javascripts/kroki.js