name: Backup Notes

on:
  schedule:
    # Backup daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Backup to GitHub
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            cd ${{ secrets.NOTES_PATH || '/home/notes/boroy-docs' }}
            
            echo "📦 Creating backup..."
            
            # Check for any uncommitted changes
            if [[ -n $(git status -s) ]]; then
              echo "📝 Found uncommitted changes, backing up..."
              
              # Add all changes
              git add .
              
              # Commit with timestamp
              git commit -m "Auto-backup: $(date '+%Y-%m-%d %H:%M:%S')"
              
              # Push to GitHub
              git push origin main
              
              echo "✅ Backup completed successfully!"
            else
              echo "ℹ️  No changes to backup"
            fi
            
            # Create local tar backup as well
            BACKUP_DIR="/home/backups/notes"
            mkdir -p $BACKUP_DIR
            
            tar -czf "$BACKUP_DIR/notes-backup-$(date +%Y%m%d-%H%M%S).tar.gz" \
                --exclude='.git' \
                --exclude='site' \
                --exclude='node_modules' \
                .
            
            # Keep only last 7 days of backups
            find $BACKUP_DIR -name "notes-backup-*.tar.gz" -mtime +7 -delete
            
            echo "💾 Local backup also created in $BACKUP_DIR"