name: Self-Hosted Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - 'docker-compose.prod.yml'
  workflow_dispatch:

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    if: github.repository == 'asbor/boroy-docs'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy to Self-Hosted Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            # Navigate to notes directory
            cd ${{ secrets.NOTES_PATH || '/home/notes/boroy-docs' }}
            
            # Pull latest changes
            git fetch origin
            git reset --hard origin/main
            
            # Update containers
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --force-recreate
            
            # Clean up old images
            docker image prune -f
            
            # Check service health
            sleep 10
            docker compose -f docker-compose.prod.yml ps
            
            echo "✅ Notes deployment completed successfully!"

  notify-success:
    needs: deploy-to-server
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Success Notification
        run: |
          echo "🎉 Personal notes deployed successfully!"
          echo "📝 Access your notes at: http://${{ secrets.SERVER_HOST }}:8080"

  notify-failure:
    needs: deploy-to-server
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Failure Notification
        run: |
          echo "❌ Deployment failed!"
          echo "🔍 Check the logs for details."